spring:
  application:
    name: spring-ai-rag
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documents-to-load:
      - classpath:/movies500.csv
